```{r, include=FALSE}
library(pocr)
library(lubridate)
library(RODBC)
library(dplyr)
library(stringr)

# # annie <- odbcConnect("test_annie")

source("select_db.R")

sp_call <- stored_procedure('ooh_pit_rates')
sp_query <- sqlQuery(con, sp_call)
clean_query <- cr_clean(sp_query, date.type = 2)
names(clean_query)[2] = "rate"
clean_query = mutate(clean_query, rate = round(rate, 1))

# code for highlights

max_data <- filter(clean_query, date == max(date))
min_data <- filter(clean_query, date == min(date))

# close connection
odbcCloseAll()

```
{  
   "title":"Children in Out-of-Home Care (Rate)",
   "subtitle":"On the First Day of the Year or Quarter",
   "img":"",
   "type":"visualization",
   "slug":"ooh-rates",
   "visualizationType":"graph",
   "tags":[ 
      "permanency",
      "out-of-home",
      "foster care",
      "county",
      "age",
      "race/ethnicity"
   ],
   "blurb":"The number of children in out-of-home care per 1,000 children on the first day of the year or quarter.",
   "unit":"Number of children in out-of-home care per 1,000 children",
   "config":{  
      "table":"sp_ooh_pit_rates",
      "transform":{  
         "Function":"daterow",
         "dateField":"Date",
         "valueFields":[  
            "Total in Out-of-Home Care 1st Day"
         ],
         "removeFields":[]
      },
      "controls":[  
         "qry_type_first_all",
         "date_type_pit"
      ],
      "params":[  
         "dynamicMonthStart",
         "pitAgeCensus",
         "ethnicityCensus",
         "gender",
         "initSetng",
         "longSetng",
         "pitCounty",
         "ooh_los",
         "nbr_placement",
         "ihs_services_ooh",
         "reporter_type",
         "access_type",
         "allegation",
         "finding",
         "dependency_cd"
      ],
      "dateParams":[],
      "requiredParams":[  
         "dynamicMonthStart"
      ],
      "showAllOthers":true,
      "returnRowHeaders":[  
         0,
         1,
         4,
         6,
         8,
         10,
         12,
         14,
         16,
         18,
         20,
         22,
         24,
         26,
         28,
         30
      ],
      "returnRowDateHeaders":[  
         0
      ],
      "returnRowControlHeaders":[  
         1
      ],
      "headerNames":[  
         "&nbsp;",
         "*qry_type_first_all",
         "Age Grouping=pitAgeCensus",
         "Gender=gender",
         "Race/Ethnicity",
         "Initial Placement=initSetng",
         "Longest Placement=longSetng",
         "County=pitCounty",
         "Dependency=dependency_cd",
         "Length of Service Desc=ooh_los",
         "Placement Count Desc=nbr_placement",
         "In-Home Service Desc=ihs_services_ooh",
         "Reporter Desc=reporter_type",
         "Access type desc=access_type",
         "Allegation=allegation",
         "Finding=finding"
      ],
      "returnRowStart":31,
      "hideRow":"allEmpty",
      "chartType":"line",
      "labels":{  
         "x":"",
         "y":""
      },
      "numberFormat":{  
         "fractionDigits":2
      }
   }
}

### Data Highlights

<div class="stat">
    <h4>`r pretty_date(max_data$date)`</h4>
    <p>`r max_data$rate`</p>
</div>

<div class="stat">
    <h4>`r pretty_date(min_data$date)`</h4>
    <p>`r min_data$rate`</p>
</div>

### Summary

This graph presents the number of children who were in out-of-home care, per 1,000 children in the general population, on the first day of each year or quarter. 

#### Questions this graph can answer

- How many children per 1,000 were in out-of-home care on a given day?

- How has the out-of-home care population changed over time?

#### See also

- [Children in Out-of-Home Care (Count)](https://portal.cssat.org/visualizations/ooh-counts), for the number of children in out-of-home care.

- [Children Entering Out-of-Home Care (Rate)](https://portal.cssat.org/visualizations/ooh-entry-rates), for the rate at which children entered care over the course of a year or quarter.


### Notes

To filter for longer episode durations, use the advanced filter *duration of out-of-home stay*.
