```{r, include=FALSE}
library(pocr)
library(lubridate)
library(RODBC)
library(dplyr)
library(stringr)

con <- odbcConnect("test_annie")

results <- sqlQuery(con, "call sp_mp_adoption('0')")
names(results) <- make.names(str_replace_all(tolower(names(results)), '\\(|\\)', ''))

results$fiscal.year.year.child.became.legally.free <- as.Date(results$fiscal.year.year.child.became.legally.free)

# code for highlights

# most recent year
recent_date <- pretty_date(filter(results, fiscal.year.year.child.became.legally.free == max(fiscal.year.year.child.became.legally.free), region == 0)$fiscal.year.year.child.became.legally.free)
recent_data <- round(filter(results, fiscal.year.year.child.became.legally.free == max(fiscal.year.year.child.became.legally.free), region == 0)$percent)

# lowest
lowest_data <- filter(results, region == 0) %>% filter(percent == min(percent)) %>% select(-region)

# highest

highest_data <- filter(results, region == 0) %>% filter(percent == max(percent)) %>% select(-region)

# close connection
odbcCloseAll()

```

{  
   "title":"Timely Adoption",
   "subtitle":"Within One Year of Becoming Legally Free",
   "img":"",
   "type":"visualization",
   "visualizationType":"graph",
   "tags":[  
      "permanency",
      "cfsr",
      "adoption",
      "annual report",
      "region"
   ],
   "blurb":"Children adopted within one year of becoming legally free.",
   "slug":"timely-adoption",
   "unit":"Percent",
   "config":{  
      "table":"sp_mp_adoption",
      "transform":{  
         "Function":"daterow",
         "dateField":"Fiscal Year/Year Child Became Legally Free",
         "valueFields":[  
            "Percent"
         ],
         "removeFields":[]
      },
      "controls":[  
         "region"
      ],
      "params":[  
         "dynamicMonthStart"
      ],
      "dateParams":[],
      "requiredParams":[  
         "dynamicMonthStart"
      ],
      "showAllOthers":true,
      "returnRowHeaders":[  
         1
      ],
      "returnRowDateHeaders":[],
      "returnRowControlHeaders":[  
         1
      ],
      "headerNames":[  
         "&nbsp;",
         "Region*region"
      ],
      "returnRowStart":2,
      "chartType":"line",
      "labels":{  
         "x":"",
         "y":"",
         "yFormat":"##'%"
      },
      "numberFormat":{  
         "fractionDigits":2,
         "suffix":"%"
      }
   }
}

### Data Highlights

<div class="stat">
    <h4>Recent: `r recent_date`</h4>
    <p>`r recent_data`%</p>
</div>

<div class="stat">
    <h4>Low: `r pretty_date(lowest_data[,1])`</h4>
    <p>`r round(lowest_data[,2])`%</p>
</div>

<div class="stat">
    <h4>High: `r pretty_date(highest_data[,1])`</h4>
    <p>`r round(highest_data[,2])`%</p>
</div>

### Summary

This graph examines the percentage of children that were adopted within one year of becoming legally free. Children are considered legally free once their legal parents' parental rights have been terminated.

#### Questions this graph can answer

- Has timely adoption been impacted by location?

- Has the timeliness of adoptions changed over time?

#### See also

- [Permanency Count](https://portal.cssat.org/visualizations/permanency-counts), for a comparison of the number of children who exit to different permanency outcomes.

- [Permanency Outcomes](https://portal.cssat.org/visualizations/permanency-cohort), for a comparison of different permanency outcomes by the length of time a child was in out-of-home care.

### Notes

The Adoptions & Safe Families Act of 1997 requires all states to hold a first permanency hearing within 12 months of the date the child entered out-of-home care. States are also required to file a petition to terminate parental rights for children in care for 15 of the most recent 22 months, unless the court determines there are compelling reasons not to file.

Like the federal [CFSR](http://partnersforourchildren.org/resources/glossary#155) measure, this percent is calculated by dividing the number of children adopted within a given by all the children who became legally free in that same year.




