```{r, include=FALSE}
library(pocr)
library(lubridate)
library(RODBC)
library(dplyr)
library(stringr)

con <- odbcConnect("test_annie")

results <- sqlQuery(con, "call sp_mp_rate_placement_order_ts()")
names(results) <- make.names(str_replace_all(tolower(names(results)), '\\(|\\)', ''))

# code for highlights

zero_reports <- filter(results, region == 0, order == 0, month.year.of.ordered.placement == max(month.year.of.ordered.placement))
one_reports <- filter(results, region == 0, order == 1, month.year.of.ordered.placement == max(month.year.of.ordered.placement))
two_reports <- filter(results, region == 0, order == 2, month.year.of.ordered.placement == max(month.year.of.ordered.placement))

# close connection
odbcCloseAll()

```
{  
   "title":"Placement Rate by Prior Placements",
   "subtitle":"Per 1,000 Households with Prior Placements",
   "img":"",
   "type":"visualization",
   "visualizationType":"graph",
   "tags":[  
      "safety",
      "annual report",
      "region",
      "out-of-home",
      "placement",
      "foster care",
      "cps"
   ],
   "keywords": [
      "intakes",
      "referrals"
   ],
   "blurb":"Screened-in reports that led to out-of-home placement, by prior placement.",
   "slug":"placement-rate-order",
   "unit":"Households with Placement per 1,000 Screened-In Reports",
   "config":{  
      "table":"sp_mp_rate_placement_order_ts",
      "transform":{  
         "Function":"daterow",
         "dateField":"Month/Year of Ordered Placement",
         "valueFields":[  
            "Scatterplot (Actual Values)",
            "Trend Line (Seasonally Adjusted)"
         ],
         "removeFields":[]
      },
      "controls":[  
         "region",
         "order"
      ],
      "params":[],
      "dateParams":[],
      "requiredParams":[],
      "showAllOthers":true,
      "returnRowHeaders":[  
         0,
         1,
         2
      ],
      "returnRowDateHeaders":[  
         0
      ],
      "returnRowControlHeaders":[  
         1,
         2
      ],
      "headerNames":[  
         "&nbsp;",
         "Region*region",
         "Order*order"
      ],
      "returnRowStart":3,
      "hideRow":"allEmpty",
      "columnClusterSize":2,
      "numberFormat":[  
         {  
            "fractionDigits":2
         }
      ],
      "multicharts":{  
         "Trend-Line":[  
            {  
               "chartType":"line",
               "chartId":"chart1",
               "labels":{  
                  "x":"",
                  "y":"",
                  "yFormat":"#,##0"
               },
               "hideColumns":[  
                  0
               ]
            }
         ],
         "Trend-Line-with-Scatterplot":[  
            {  
               "chartType":"combo",
               "chartId":"chart1",
               "labels":{  
                  "x":"",
                  "y":""
               },
               "hideColumns":[]
            }
         ],
         "Scatterplot":[  
            {  
               "chartType":"scatterChart",
               "chartId":"chart1",
               "labels":{  
                  "x":"",
                  "y":"",
                  "yFormat":"#,##0"
               },
               "hideColumns":[  
                  1
               ]
            }
         ]
      }
   }
}

### Data Highlights

<div class="stat">
    <h4>No Prior Reports</h4>
    <p>`r round(zero_reports$scatterplot.actual.values)`</p>
</div>

<div class="stat">
    <h4>One Prior Report</h4>
    <p>`r round(one_reports$scatterplot.actual.values)`</p>
</div>

<div class="stat">
    <h4>Two Prior Reports</h4>
    <p>`r round(two_reports$scatterplot.actual.values)`</p>
</div>

### Summary

This graph shows the rate at which screened-in reports---reports that receive an investigation or other service---led to an out-of-home placement, and how this varies with prior system contact.

#### Questions this graph can answer

- For a household with a new screened-in report, how has the risk of placement change based on a history of prior placements?

#### See also

- [Screening Rate](https://portal.cssat.org/visualizations/screening-rate), for the rate at which reports were screened-in for investigation or other services.

- [Out-of-Home Entries (Rates)](https://portal.cssat.org/visualizations/ooh-entry-rates), for the population-based rate of placements.

### Notes

The rate of placements with no (zero) prior placements is calculated by dividing the number of households with a first placement in a given month by the number of households with screened-in reports who had no prior placements at the start of the month.

The rate of placements with one prior placement is calculated by dividing the number of households with a second placement in a given month by the number of households with screened-in reports who had one prior placement at the start of the month, and so on.

A household is considered to have had a placement if *one or more* children in the household entered out-of-home care.

Additional reports were only counted if there had been more than 48 hours since the previous report about the same household.

